apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: high-cpu-alerts
  namespace: monitoring
spec:
  groups:
    - name: cpu-usage.rules
      rules:
        - alert: HighCPUUsage
          expr: sum(rate(container_cpu_usage_seconds_total[5m])) by (pod) > 0.9
          for: 2m
          labels:
            severity: critical
          annotations:
            summary: "High CPU usage detected"
            description: "Pod {{ $labels.pod }} is using high CPU. Current usage: {{ $value }} cores."
